name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-jdk@v2
      with:
        java-version: '4' # The OpenJDK version to make available on the path
        architecture: 'x64' # defaults to 'x64'
    - run: java -cp java HelloWorldApp
